---
# Node.js Installation
- name: Install build dependencies
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - curl
    state: present
  tags:
    - nodejs
    - development

- name: Download n installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tj/n/master/bin/n
    dest: /tmp/n
    mode: '0755'
  tags:
    - nodejs
    - development

- name: Install n
  become: true
  ansible.builtin.command: /tmp/n lts
  args:
    creates: /usr/local/bin/n
  tags:
    - nodejs
    - development

- name: Install latest npm
  become: true
  ansible.builtin.command: npm install -g npm@latest
  changed_when: false
  tags:
    - nodejs
    - development