---
- name: Ensure /opt/appimage folder exists
  become: true
  ansible.builtin.file:
    state: directory
    path: "/opt/appimage"
    mode: '0755'

- name: "Download AppImage file for {{ appimage_alias }}"
  become: true
  ansible.builtin.get_url:
    url: "{{ appimage_url }}"
    dest: "/opt/appimage/{{ appimage_url | basename }}"
    mode: '0755'
  register: new_appimage

- name: "Remove existing symlink if exists"
  become: true
  ansible.builtin.file:
    path: "/usr/local/bin/{{ appimage_alias }}"
    state: absent
  when: new_appimage is changed

- name: "Create wrapper script for {{ appimage_alias }}"
  become: true
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      /opt/appimage/{{ appimage_url | basename }} {% if appimage_flags is defined %}{{ appimage_flags }}{% endif %} "$@"
    dest: "/usr/local/bin/{{ appimage_alias }}"
    mode: '0755'

