---
# Tasks file for jcminarro-environment
# This role sets up a complete development environment with essential tools and applications
# It includes:
# - Development tools and IDEs
# - System utilities
# - Communication apps
# - Security tools
# - Terminal enhancements

# Repository and Keys Configuration
- name: Create keyrings directory
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags:
    - repositories
    - security

- name: Install GPG/ASC keys
  become: true
  ansible.builtin.apt_key:
    url: "{{ item.url }}"
    keyring: "/etc/apt/keyrings/{{ item.filename }}.gpg"
    state: present
  with_items:
    - url: "https://download.sublimetext.com/sublimehq-pub.gpg"
      filename: sublimehq-pub
    - url: "https://downloads.1password.com/linux/keys/1password.asc"
      filename: 1password
    - url: "https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg"
      filename: tailscale
  tags:
    - repositories
    - security

- name: Add specified repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: present
    filename: "{{ item.filename }}"
    update_cache: true
  with_items:
    - repo: "deb [signed-by=/etc/apt/keyrings/sublimehq-pub.gpg] https://download.sublimetext.com/ apt/stable/"
      filename: sublime
    - repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/1password.gpg] https://downloads.1password.com/linux/debian/amd64 stable main"
      filename: 1Password
    - repo: "deb [signed-by=/etc/apt/keyrings/tailscale.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
      filename: tailscale
  tags:
    - repositories

# System Package Installation
- name: Install system packages
  become: true
  ansible.builtin.apt:
    name: "{{ system_packages }}"
    state: present
    update_cache: true
  vars:
    system_packages:
      # Development Tools
      - vim
      - git
      - jq
      - colordiff
      
      # Editors
      - sublime-text
      
      # System Utilities
      - btop
      - htop
      - iperf3
      - nmap
      - zip
      - unzip
      - xz-utils
      - aptitude
      - libfuse2t64
      - wireguard
      - sshpass
      
      # Terminal
      - guake
      
      # Security
      - 1password

      # Multimedia
      - gimp
      - peek
      - vlc

      # Network Tools
      - tailscale
      - traceroute

      # Screenshot Tools
      - flameshot

  tags:
    - packages
    - system

# AppImage Installation
- name: Install AppImages
  ansible.builtin.include_tasks: install_appimage.yml
  vars:
    - appimage_url: "{{ item.appimage_url }}"
    - appimage_alias: "{{ item.appimage_alias }}"
    - appimage_flags: "{{ item.appimage_flags | default('') }}"
  with_items:
    - appimage_url: "https://github.com/nextcloud-releases/desktop/releases/download/v3.16.0/Nextcloud-3.16.0-x86_64.AppImage"
      appimage_alias: nextcloud
    - appimage_url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.8.10/Obsidian-1.8.10.AppImage"
      appimage_alias: obsidian
      appimage_flags: "--no-sandbox"
  tags:
    - appimages

# Snap Package Installation
- name: Install Snap Packages
  become: true
  community.general.snap:
    name: "{{ communication_apps }}"
    state: present
  vars:
    communication_apps:
      - slack
      - telegram-desktop
      - zoom-client
      - discord
  tags:
    - snaps
    - communication

# Development Tools Installation
- name: Install SDK Man
  include_role:
    name: gantsign.sdkman
  vars:
    sdkman_users:
      - "{{ lookup('env', 'USER') }}"
  tags:
    - development
    - sdkman

- name: Install Google Chrome
  include_role:
    name: darkwizard242.googlechrome
  vars:
    ansible_become: true
  tags:
    - browsers

- name: Install VS Code
  include_role:
    name: darkwizard242.vscode
  vars:
    ansible_become: true
  tags:
    - development
    - vscode

# Install Anki
- name: Install Anki
  ansible.builtin.include_tasks: install_anki.yml
  tags:
    - anki

# Install Docker
- name: Install Docker
  ansible.builtin.include_tasks: install_nodejs.yml
  tags:
    - nodejs
    - development

# Install Docker
- name: Install Docker
  ansible.builtin.include_tasks: install_docker.yml
  tags:
    - docker
    - development
