---
# Tasks file for jcminarro-environment
# This role sets up a complete development environment with essential tools and applications
# It includes:
# - Development tools and IDEs
# - System utilities
# - Communication apps
# - Security tools
# - Terminal enhancements

# Repository and Keys Configuration
- name: Install GPG/ASC keys
  become: true
  ansible.builtin.apt_key:
    url: "{{ item.url }}"
    keyring: "{{ item.keyring }}"
    state: present
  with_items:
    - url: "https://download.sublimetext.com/sublimehq-pub.gpg"
      keyring: /etc/apt/trusted.gpg.d/sublimehq-pub.gpg
    - url: "https://downloads.1password.com/linux/keys/1password.asc"
      keyring: /etc/apt/trusted.gpg.d/1password.gpg
  tags:
    - repositories
    - security

- name: Add repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: present
    filename: "{{ item.filename }}"
    update_cache: true
  with_items:
    - repo: "deb https://download.sublimetext.com/ apt/stable/"
      filename: sublime
    - repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/1password.gpg] https://downloads.1password.com/linux/debian/amd64 stable main"
      filename: 1Password
  tags:
    - repositories

# System Package Installation
- name: Install system packages
  become: true
  ansible.builtin.apt:
    name: "{{ system_packages }}"
    state: present
    update_cache: true
  vars:
    system_packages:
      # Development Tools
      - vim
      - git
      - jq
      
      # Editors
      - sublime-text
      
      # System Utilities
      - btop
      - htop
      - iperf3
      - nmap
      - zip
      - unzip
      - aptitude
      - libfuse2t64
      
      # Terminal
      - guake
      
      # Security
      - 1password
  tags:
    - packages
    - system

# AppImage Installation
- name: Install AppImages
  ansible.builtin.include_tasks: install_appimage.yml
  vars:
    - appimage_url: "{{ item.appimage_url }}"
    - appimage_alias: "{{ item.appimage_alias }}"
  with_items:
    - appimage_url: "https://github.com/nextcloud-releases/desktop/releases/download/v3.16.0/Nextcloud-3.16.0-x86_64.AppImage"
      appimage_alias: nextcloud
  tags:
    - appimages

# Snap Package Installation
- name: Install Snap Packages
  become: true
  community.general.snap:
    name: "{{ communication_apps }}"
    state: present
  vars:
    communication_apps:
      - slack
      - telegram-desktop
      - zoom-client
      - discord
  tags:
    - snaps
    - communication

# Development Tools Installation
- name: Install SDK Man
  include_role:
    name: gantsign.sdkman
  vars:
    sdkman_users:
      - "{{ lookup('env', 'USER') }}"
  tags:
    - development
    - sdkman

- name: Install Google Chrome
  include_role:
    name: darkwizard242.googlechrome
  vars:
    ansible_become: true
  tags:
    - browsers


# Install Anki
- name: Install Anki
  ansible.builtin.include_tasks: install_anki.yml
  tags:
    - anki
