---
# Configure SSH

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ ssh_directory }}"
    state: directory
    mode: '0700'

- name: Ensure SSH config file exists
  ansible.builtin.file:
    path: "{{ ssh_config_file }}"
    state: touch
    mode: '0600'

- name: Add common SSH config
  ansible.builtin.blockinfile:
    path: "{{ ssh_config_file }}"
    block: |
      # Default settings
      Host *
          IdentityAgent ~/.1password/agent.sock
          IdentitiesOnly yes
          ServerAliveInterval 60
          ServerAliveCountMax 20
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Common Settings"
    create: true
    mode: '0600'
  when: configure_ssh | bool
