---
# Install AppImages

- name: Ensure AppImage directory exists
  ansible.builtin.file:
    path: /opt/appimage
    state: directory
    mode: '0755'

- name: Download AppImage files
  ansible.builtin.get_url:
    url: "{{ item.appimage_url }}"
    dest: "/opt/appimage/{{ item.appimage_url | basename }}"
    mode: '0755'
  loop: "{{ appimages }}"

- name: Create wrapper scripts for AppImages
  ansible.builtin.template:
    src: appimage-wrapper.j2
    dest: "/usr/local/bin/{{ item.appimage_alias }}"
    mode: '0755'
  loop: "{{ appimages }}"