---
# Handlers for jcminarro-environment

# Linux handlers
- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true
  become: true

- name: Update MIME database
  become: true
  ansible.builtin.command: update-mime-database /usr/share/mime
  changed_when: true

# macOS handlers
- name: Restart Finder
  ansible.builtin.command: killall Finder
  ignore_errors: true
