---
# Install AppImages

- name: Ensure AppImage directory exists
  become: true
  ansible.builtin.file:
    path: /opt/appimage
    state: directory
    mode: '0755'

- name: Check installed AppImage files
  ansible.builtin.stat:
    path: "/opt/appimage/{{ item.appimage_url | basename }}"
  loop: "{{ appimages }}"
  register: installed_appimages

- name: Download AppImage files
  become: true
  ansible.builtin.get_url:
    url: "{{ item.item.appimage_url }}"
    dest: "/opt/appimage/{{ item.item.appimage_url | basename }}"
    mode: '0755'
  loop: "{{ installed_appimages.results }}"
  when: not item.stat.exists
  retries: 3
  delay: 10
  until: appimage_download is succeeded
  register: appimage_download

- name: Create wrapper scripts for AppImages
  become: true
  ansible.builtin.template:
    src: appimage-wrapper.j2
    dest: "/usr/local/bin/{{ item.appimage_alias }}"
    mode: '0755'
  loop: "{{ appimages }}"
