---
# Include Galaxy roles for Linux

- name: Include gantsign.sdkman role
  ansible.builtin.include_role:
    name: gantsign.sdkman
  vars:
    sdkman_users: "{{ sdkman_users }}"

- name: Include darkwizard242.googlechrome role
  ansible.builtin.include_role:
    name: darkwizard242.googlechrome
  vars:
    ansible_become: true

- name: Include darkwizard242.vscode role
  ansible.builtin.include_role:
    name: darkwizard242.vscode
  vars:
    ansible_become: true

- name: Include darkwizard242.onepassword role
  ansible.builtin.include_role:
    name: darkwizard242.onepassword
  vars:
    onepassword_desired_state: latest
